[System.Serializable]
public enum EVENT_TYPE
{
    FIGHT,
    PATH,
    TRAP_LOSE_HEALTH,
    BANDITS_STEAL_GOLD,
    WISHING_WELL_DAMAGE_BOOST,
    WISHING_WELL_HEALTH_REGEN,
    WISHING_WELL_GAIN_GOLD
}
